version: '3'

tasks:
  build:web:
    desc: Build the Flutter application
    cmds:
      - flutter build web

  build:android:
    desc: Build the Android application
    cmds:
      - flutter build appbundle --release

  build:android:release:
    desc: Build the Android application
    cmds:
      - task: clean
      - task: get
      - task: build:android

  deploy:
    desc: Deploy the application to Firebase Hosting
    deps:
      - build
    cmds:
      - firebase deploy --only hosting

  serve:web:
    desc: Serve the application locally
    cmds:
      - flutter run -d chrome

  serve:linux:
    desc: Serve the application on Linux
    cmds:
      - flutter run -d linux

  serve:clean:
    desc: Clean and serve the application
    cmds:
      - task: clean
      - task: get
      - task: serve:web

  clean:
    desc: Clean the Flutter build cache
    cmds:
      - flutter clean

  get:
    desc: Get Flutter dependencies
    cmds:
      - flutter pub get

  upgrade:
    desc: Upgrade Flutter dependencies
    cmds:
      - flutter pub upgrade

  analyze:
    desc: Analyze the Flutter code
    cmds:
      - flutter analyze

  test:
    desc: Run Flutter tests
    cmds:
      - flutter test

  # format:
  #   desc: Format the Flutter code
  #   cmds:
  #     - flutter format .

  lint:
    desc: Run Flutter linting
    cmds:
      - flutter analyze --no-fatal-infos --no-fatal-warnings

  firebase:login:
    desc: Log in to Firebase
    cmds:
      - firebase login

  firebase:init:
    desc: Initialize Firebase in the project
    cmds:
      - firebase init

  firebase:emulators:start:
    desc: Start Firebase emulators
    cmds:
      - firebase emulators:start

  firebase:emulators:exec:
    desc: Execute a command with Firebase emulators running
    cmds:
      - firebase emulators:exec "{{.CLI_ARGS}}"

  firebase:functions:deploy:
    desc: Deploy Firebase functions
    cmds:
      - firebase deploy --only functions

  firebase:firestore:rules:deploy:
    desc: Deploy Firestore security rules
    cmds:
      - firebase deploy --only firestore:rules

  firebase:storage:rules:deploy:
    desc: Deploy Cloud Storage security rules
    cmds:
      - firebase deploy --only storage:rules

  firebase:hosting:deploy:
    desc: Deploy Firebase Hosting
    cmds:
      - firebase deploy --only hosting

  firebase:deploy:all:
    desc: Deploy all Firebase services
    cmds:
      - firebase deploy

  validate:
    desc: Validate code quality, linting, tests, and build
    cmds:
      - task: analyze
      # - task: format
      - task: lint
      - task: test
      - task: build

  generate_icons:
    desc: Generate app icons and favicon for all platforms using flutter_launcher_icons
    cmds:
      - dart run flutter_launcher_icons

  update_icons:
    desc: Update app icons using flutter_launcher_icons
    cmds:
      - flutter pub run flutter_launcher_icons:main
