// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjueiqAbXpZJgwzXLAHoQQpglzw6enKSo',
    appId: '1:77707132862:web:8733a18dd01c36839083ef',
    messagingSenderId: '77707132862',
    projectId: 'enl-parenting',
    authDomain: 'enl-parenting.firebaseapp.com',
    storageBucket: 'enl-parenting.firebasestorage.app',
    measurementId: 'G-HJL7KV60XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRIwF8LrQjAz0Q80jjql42uOuL9BfLOkI',
    appId: '1:77707132862:android:15973ea2e4c6b0ed9083ef',
    messagingSenderId: '77707132862',
    projectId: 'enl-parenting',
    storageBucket: 'enl-parenting.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXQgF4xMqoeEof-x1xwMimFb8PHzchidw',
    appId: '1:77707132862:ios:030d9acd604467dd9083ef',
    messagingSenderId: '77707132862',
    projectId: 'enl-parenting',
    storageBucket: 'enl-parenting.firebasestorage.app',
    iosBundleId: 'com.garciaericn.homeharmony',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXQgF4xMqoeEof-x1xwMimFb8PHzchidw',
    appId: '1:77707132862:ios:030d9acd604467dd9083ef',
    messagingSenderId: '77707132862',
    projectId: 'enl-parenting',
    storageBucket: 'enl-parenting.firebasestorage.app',
    iosBundleId: 'com.garciaericn.homeharmony',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjueiqAbXpZJgwzXLAHoQQpglzw6enKSo',
    appId: '1:77707132862:web:53bd50b874d69c1b9083ef',
    messagingSenderId: '77707132862',
    projectId: 'enl-parenting',
    authDomain: 'enl-parenting.firebaseapp.com',
    storageBucket: 'enl-parenting.firebasestorage.app',
    measurementId: 'G-PTKEKDCQQR',
  );
}
